[package]
name = "mtga_resources_locator"
version = "0.1.0"
authors = ["Michele Gargiulo <michele@grg.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.0"
