name: Windows Testing

on:
  push:
    branches:
        - master
        - gh-actions
  pull_request:
    branches:
        - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add fake registry key
      run: REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Wizards of the Coast\MTGArena" /f /v Path /t REG_SZ /d "C:\Magic"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
